{% set name = "svgpathtools" %}
{% set version = "1.6.1" %}
{% set sha256 = "7054e6de1953e295bf565d535d585695453b09f8db4a2f7c4853348732097a3e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - svgwrite

test:
  requires:
    - python {{ python_min }}
  source_files:
    - test
  commands:
    # One unit test currently fails under Windows. See also:
    #     https://github.com/conda-forge/staged-recipes/pull/15429#issuecomment-869240403
    - python -m unittest discover test  # [not win]
  imports:
    - svgpathtools

about:
  home: https://github.com/mathandy/svgpathtools
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - LICENSE2.txt
  summary: Tools for manipulating and analyzing SVG Path objects and Bezier curves
  description: |
    svgpathtools is a collection of tools for manipulating and analyzing SVG
    Path objects and Bézier curves.

    svgpathtools contains functions designed to easily read, write and display
    SVG files as well as a large selection of geometrically-oriented tools to
    transform and analyze path elements.

    Additionally, the submodule bezier.py contains tools for for working with
    general nth order Bezier curves stored as n-tuples.
  doc_url: https://github.com/mathandy/svgpathtools/blob/master/README.md
  dev_url: https://github.com/mathandy/svgpathtools

extra:
  recipe-maintainers:
    - leycec
    - mathandy
